// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_training/test/domain/use_cases/fetch_weather_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:flutter_riverpod/flutter_riverpod.dart' as _i3;
import 'package:flutter_training/data/repositories/weather_repository.dart'
    as _i5;
import 'package:flutter_training/data/repositories/weather_ui_state_repository.dart'
    as _i6;
import 'package:flutter_training/models/weather_response.dart' as _i2;
import 'package:flutter_training/presentation/ui_state/weather_page_ui_state.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeWeatherResponse_0 extends _i1.SmartFake
    implements _i2.WeatherResponse {
  _FakeWeatherResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNotifierProviderRef_1<T> extends _i1.SmartFake
    implements _i3.NotifierProviderRef<T> {
  _FakeNotifierProviderRef_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWeatherPageUiState_2 extends _i1.SmartFake
    implements _i4.WeatherPageUiState {
  _FakeWeatherPageUiState_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [WeatherRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherRepository extends _i1.Mock implements _i5.WeatherRepository {
  MockWeatherRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.WeatherResponse fetchWeather({
    required String? area,
    required DateTime? date,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchWeather, [], {#area: area, #date: date}),
            returnValue: _FakeWeatherResponse_0(
              this,
              Invocation.method(#fetchWeather, [], {#area: area, #date: date}),
            ),
          )
          as _i2.WeatherResponse);
}

/// A class which mocks [WeatherUiStateRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherUiStateRepository extends _i1.Mock
    implements _i6.WeatherUiStateRepository {
  MockWeatherUiStateRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.NotifierProviderRef<_i4.WeatherPageUiState> get ref =>
      (super.noSuchMethod(
            Invocation.getter(#ref),
            returnValue: _FakeNotifierProviderRef_1<_i4.WeatherPageUiState>(
              this,
              Invocation.getter(#ref),
            ),
          )
          as _i3.NotifierProviderRef<_i4.WeatherPageUiState>);

  @override
  _i4.WeatherPageUiState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeWeatherPageUiState_2(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i4.WeatherPageUiState);

  @override
  set state(_i4.WeatherPageUiState? value) => super.noSuchMethod(
    Invocation.setter(#state, value),
    returnValueForMissingStub: null,
  );

  @override
  _i4.WeatherPageUiState build() =>
      (super.noSuchMethod(
            Invocation.method(#build, []),
            returnValue: _FakeWeatherPageUiState_2(
              this,
              Invocation.method(#build, []),
            ),
          )
          as _i4.WeatherPageUiState);

  @override
  void updateWeather({
    required String? weatherCondition,
    required int? minTemperature,
    required int? maxTemperature,
  }) => super.noSuchMethod(
    Invocation.method(#updateWeather, [], {
      #weatherCondition: weatherCondition,
      #minTemperature: minTemperature,
      #maxTemperature: maxTemperature,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void setLoading({required bool? isLoading}) => super.noSuchMethod(
    Invocation.method(#setLoading, [], {#isLoading: isLoading}),
    returnValueForMissingStub: null,
  );

  @override
  void setError(String? errorMessage) => super.noSuchMethod(
    Invocation.method(#setError, [errorMessage]),
    returnValueForMissingStub: null,
  );

  @override
  void clearError() => super.noSuchMethod(
    Invocation.method(#clearError, []),
    returnValueForMissingStub: null,
  );

  @override
  void listenSelf(
    void Function(_i4.WeatherPageUiState?, _i4.WeatherPageUiState)? listener, {
    void Function(Object, StackTrace)? onError,
  }) => super.noSuchMethod(
    Invocation.method(#listenSelf, [listener], {#onError: onError}),
    returnValueForMissingStub: null,
  );

  @override
  bool updateShouldNotify(
    _i4.WeatherPageUiState? previous,
    _i4.WeatherPageUiState? next,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateShouldNotify, [previous, next]),
            returnValue: false,
          )
          as bool);
}
